### ISSUE TITLE
Request: Cut release with zstd git branch fix

### ISSUE THREAD

**Issue by Doerge** [silviucpp/ezstd#13]
This commit already fixes an issue where a branch has been renamed/deleted in the FB repo:
https://github.com/silviucpp/ezstd/commit/771ea0beb9f3834d66b84e8e56802b1f527bc27e

Would it be possible to make a hexpm https://hex.pm/packages/ezstd release with this commit?

Thanks for the project! 🙏

**Comment by silviucpp** [comment]
I published the release
